RULES = {
    "python": [
        {"regex": r"\beval\(", "desc": "Dangerous use of eval()", "cwe": "CWE-94", "severity": "Critical"},
        {"regex": r"\bexec\(", "desc": "Arbitrary code execution via exec()", "cwe": "CWE-94", "severity": "Critical"},
        {"regex": r"os\.system\(", "desc": "Command execution via os.system()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"subprocess\.(Popen|call|run)\(", "desc": "Command injection risk in subprocess", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"pickle\.load\(", "desc": "Insecure pickle deserialization", "cwe": "CWE-502", "severity": "High"},
        {"regex": r"marshal\.loads\(", "desc": "Untrusted deserialization via marshal", "cwe": "CWE-502", "severity": "High"},
        {"regex": r"yaml\.load\(", "desc": "Unsafe YAML load (use safe_load)", "cwe": "CWE-502", "severity": "High"},
        {"regex": r"hashlib\.md5\(", "desc": "Weak cryptographic algorithm (MD5)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"hashlib\.sha1\(", "desc": "Weak cryptographic algorithm (SHA1)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"random\.random\(", "desc": "Insecure RNG for crypto context", "cwe": "CWE-338", "severity": "Medium"},
        {"regex": r"input\(", "desc": "Unvalidated input from input()", "cwe": "CWE-20", "severity": "Low"},
        {"regex": r"flask\.app\.run\(", "desc": "Flask app running with debug=True", "cwe": "CWE-489", "severity": "High"},
        {"regex": r"Django\.settings\.DEBUG\s*=\s*True", "desc": "Django DEBUG mode enabled", "cwe": "CWE-489", "severity": "High"},
        {"regex": r"werkzeug\.run_simple\(", "desc": "Werkzeug dev server in production", "cwe": "CWE-489", "severity": "High"},
        {"regex": r"jwt\.decode\([^,]+\)", "desc": "JWT decoding without verification", "cwe": "CWE-347", "severity": "Critical"},
    ],
    "javascript": [
        {"regex": r"eval\(", "desc": "Use of eval()", "cwe": "CWE-95", "severity": "Critical"},
        {"regex": r"Function\(", "desc": "Function constructor allows dynamic code execution", "cwe": "CWE-95", "severity": "Critical"},
        {"regex": r"setTimeout\(['\"].+['\"],", "desc": "setTimeout with string arg is eval-like", "cwe": "CWE-95", "severity": "High"},
        {"regex": r"setInterval\(['\"].+['\"],", "desc": "setInterval with string arg is eval-like", "cwe": "CWE-95", "severity": "High"},
        {"regex": r"innerHTML\s*=", "desc": "Unescaped innerHTML assignment (XSS)", "cwe": "CWE-79", "severity": "Critical"},
        {"regex": r"outerHTML\s*=", "desc": "Unescaped outerHTML assignment", "cwe": "CWE-79", "severity": "High"},
        {"regex": r"document\.write\(", "desc": "DOM XSS via document.write()", "cwe": "CWE-79", "severity": "Critical"},
        {"regex": r"localStorage\.setItem\(", "desc": "Sensitive data stored in localStorage", "cwe": "CWE-922", "severity": "Medium"},
        {"regex": r"sessionStorage\.setItem\(", "desc": "Sensitive data stored in sessionStorage", "cwe": "CWE-922", "severity": "Medium"},
        {"regex": r"crypto\.createHash\(['\"]md5['\"]\)", "desc": "Weak cryptography (MD5)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"crypto\.createHash\(['\"]sha1['\"]\)", "desc": "Weak cryptography (SHA1)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"child_process\.(exec|spawn|execSync)\(", "desc": "Command injection risk in Node.js", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"\$\(.+\)\.html\(", "desc": "jQuery .html() injection sink", "cwe": "CWE-79", "severity": "Critical"},
        {"regex": r"\$\(.+\)\.append\(", "desc": "jQuery .append() injection sink", "cwe": "CWE-79", "severity": "High"},
    ],
    "json": [
        {"regex": r"\"NODE_ENV\"\s*:\s*\"development\"", "desc": "Running in dev mode", "cwe": "CWE-693", "severity": "Medium"},
        {"regex": r"\"debug\"\s*:\s*true", "desc": "Debug mode enabled in config", "cwe": "CWE-693", "severity": "Medium"},
        {"regex": r"\"jwtSecret\"\s*:\s*\".+\"", "desc": "Hardcoded JWT secret", "cwe": "CWE-798", "severity": "Critical"},
        {"regex": r"\"password\"\s*:\s*\".+\"", "desc": "Hardcoded password in config", "cwe": "CWE-798", "severity": "Critical"},
        {"regex": r"\"api_key\"\s*:\s*\".+\"", "desc": "Hardcoded API key", "cwe": "CWE-798", "severity": "High"},
        {"regex": r"\"insecure\"\s*:\s*true", "desc": "Insecure mode enabled", "cwe": "CWE-693", "severity": "High"},
    ],
    "php": [
        {"regex": r"\beval\(", "desc": "Dangerous use of eval()", "cwe": "CWE-94", "severity": "Critical"},
        {"regex": r"exec\(", "desc": "Command execution via exec()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"shell_exec\(", "desc": "Command execution via shell_exec()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"passthru\(", "desc": "Command execution via passthru()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"system\(", "desc": "Command execution via system()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"mysql_query\(", "desc": "Deprecated MySQL API vulnerable to SQLi", "cwe": "CWE-89", "severity": "Critical"},
        {"regex": r"mysqli_query\(", "desc": "Direct SQL execution without sanitization", "cwe": "CWE-89", "severity": "High"},
        {"regex": r"\$_GET\[", "desc": "Direct use of $_GET without validation", "cwe": "CWE-20", "severity": "Medium"},
        {"regex": r"\$_POST\[", "desc": "Direct use of $_POST without validation", "cwe": "CWE-20", "severity": "Medium"},
        {"regex": r"\$_COOKIE\[", "desc": "Direct use of $_COOKIE without validation", "cwe": "CWE-20", "severity": "Medium"},
        {"regex": r"include\(", "desc": "Dynamic include may allow file inclusion", "cwe": "CWE-98", "severity": "Critical"},
        {"regex": r"require\(", "desc": "Dynamic require may allow file inclusion", "cwe": "CWE-98", "severity": "Critical"},
    ],
    "yaml": [
        {"regex": r"!!python/object", "desc": "YAML unsafe object deserialization", "cwe": "CWE-502", "severity": "High"},
        {"regex": r"debug:\s*true", "desc": "Debug mode enabled in YAML config", "cwe": "CWE-693", "severity": "Medium"},
        {"regex": r"password:\s*.+", "desc": "Hardcoded password in YAML", "cwe": "CWE-798", "severity": "Critical"},
        {"regex": r"secret:\s*.+", "desc": "Hardcoded secret in YAML", "cwe": "CWE-798", "severity": "High"},
        {"regex": r"api_key:\s*.+", "desc": "Hardcoded API key in YAML", "cwe": "CWE-798", "severity": "High"},
        {"regex": r"allowInsecure:\s*true", "desc": "Insecure flag enabled in YAML config", "cwe": "CWE-693", "severity": "High"},
    ],
    "java": [
        {"regex": r"Runtime\.getRuntime\(\)\.exec\(", "desc": "Command execution in Java", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"ObjectInputStream", "desc": "Insecure deserialization with ObjectInputStream", "cwe": "CWE-502", "severity": "Critical"},
        {"regex": r"Statement\.execute\(", "desc": "SQL injection risk with Statement.execute()", "cwe": "CWE-89", "severity": "Critical"},
        {"regex": r"MessageDigest\.getInstance\(\"MD5", "desc": "Weak crypto (MD5)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"MessageDigest\.getInstance\(\"SHA1", "desc": "Weak crypto (SHA1)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"System\.setProperty\(\"DEBUG", "desc": "Debug mode enabled", "cwe": "CWE-693", "severity": "Low"},
    ],
    "csharp": [
        {"regex": r"Process\.Start\(", "desc": "Command execution via Process.Start()", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"BinaryFormatter\.Deserialize\(", "desc": "Insecure deserialization via BinaryFormatter", "cwe": "CWE-502", "severity": "Critical"},
        {"regex": r"SqlCommand\(.+\+.+\)", "desc": "SQL injection risk via string concatenation", "cwe": "CWE-89", "severity": "Critical"},
        {"regex": r"MD5CryptoServiceProvider", "desc": "Weak crypto (MD5)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"SHA1CryptoServiceProvider", "desc": "Weak crypto (SHA1)", "cwe": "CWE-327", "severity": "Medium"},
    ],
    "go": [
        {"regex": r"os\.Exec\(", "desc": "Command execution in Go", "cwe": "CWE-78", "severity": "High"},
        {"regex": r"template\.Must\(template\.New", "desc": "Unescaped HTML templates in Go", "cwe": "CWE-79", "severity": "High"},
        {"regex": r"md5\.New\(", "desc": "Weak crypto (MD5)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"sha1\.New\(", "desc": "Weak crypto (SHA1)", "cwe": "CWE-327", "severity": "Medium"},
        {"regex": r"log\.Fatal\(err\)", "desc": "Potential error leakage to logs", "cwe": "CWE-209", "severity": "Low"},
    ]
}
