RULES = {
    "python": [
        {"regex": r"\beval\(", "desc": "Dangerous use of eval()", "cwe": "CWE-94"},
        {"regex": r"\bexec\(", "desc": "Use of exec() may allow arbitrary code execution", "cwe": "CWE-94"},
        {"regex": r"os\.system\(", "desc": "Command execution via os.system()", "cwe": "CWE-78"},
        {"regex": r"subprocess\.(Popen|call|run)\(", "desc": "Potential command injection in subprocess", "cwe": "CWE-78"},
        {"regex": r"pickle\.load\(", "desc": "Insecure pickle deserialization", "cwe": "CWE-502"},
        {"regex": r"yaml\.load\(", "desc": "Unsafe YAML load (use safe_load)", "cwe": "CWE-502"},
        {"regex": r"hashlib\.md5\(", "desc": "Weak cryptographic algorithm (MD5)", "cwe": "CWE-327"},
        {"regex": r"hashlib\.sha1\(", "desc": "Weak cryptographic algorithm (SHA1)", "cwe": "CWE-327"},
        {"regex": r"random\.random\(", "desc": "Insecure random number generator for security context", "cwe": "CWE-338"},
        {"regex": r"flask\.app\.run\(", "desc": "Flask app running with debug=True", "cwe": "CWE-489"},
        {"regex": r"Django\.settings\.DEBUG\s*=\s*True", "desc": "Django app running in DEBUG mode", "cwe": "CWE-489"},
        {"regex": r"jwt\.decode\([^,]+\)", "desc": "JWT verification without signature check", "cwe": "CWE-347"},
    ],
    "javascript": [
        {"regex": r"eval\(", "desc": "Use of eval()", "cwe": "CWE-95"},
        {"regex": r"Function\(", "desc": "Use of Function constructor (like eval)", "cwe": "CWE-95"},
        {"regex": r"setTimeout\([^,]+,[^)]*\)", "desc": "setTimeout with string argument is eval-like", "cwe": "CWE-95"},
        {"regex": r"innerHTML\s*=", "desc": "Unescaped innerHTML assignment (XSS)", "cwe": "CWE-79"},
        {"regex": r"outerHTML\s*=", "desc": "Unescaped outerHTML assignment", "cwe": "CWE-79"},
        {"regex": r"document\.write\(", "desc": "Potential DOM XSS via document.write()", "cwe": "CWE-79"},
        {"regex": r"localStorage\.setItem\(", "desc": "Sensitive data stored in localStorage", "cwe": "CWE-922"},
        {"regex": r"sessionStorage\.setItem\(", "desc": "Sensitive data stored in sessionStorage", "cwe": "CWE-922"},
        {"regex": r"crypto\.createHash\(['\"]md5['\"]\)", "desc": "Weak cryptography (MD5)", "cwe": "CWE-327"},
        {"regex": r"crypto\.createHash\(['\"]sha1['\"]\)", "desc": "Weak cryptography (SHA1)", "cwe": "CWE-327"},
        {"regex": r"child_process\.(exec|spawn|execSync)\(", "desc": "Command injection risk in Node.js", "cwe": "CWE-78"},
    ],
    "json": [
        {"regex": r"\"NODE_ENV\"\s*:\s*\"development\"", "desc": "Running in dev mode", "cwe": "CWE-693"},
        {"regex": r"\"debug\"\s*:\s*true", "desc": "Debug mode enabled in config", "cwe": "CWE-693"},
        {"regex": r"\"jwtSecret\"\s*:\s*\".+\"", "desc": "Hardcoded JWT secret", "cwe": "CWE-798"},
        {"regex": r"\"password\"\s*:\s*\".+\"", "desc": "Hardcoded password in config", "cwe": "CWE-798"},
        {"regex": r"\"api_key\"\s*:\s*\".+\"", "desc": "Hardcoded API key", "cwe": "CWE-798"},
    ],
    "php": [
        {"regex": r"\beval\(", "desc": "Dangerous use of eval()", "cwe": "CWE-94"},
        {"regex": r"exec\(", "desc": "Command execution via exec()", "cwe": "CWE-78"},
        {"regex": r"shell_exec\(", "desc": "Command execution via shell_exec()", "cwe": "CWE-78"},
        {"regex": r"passthru\(", "desc": "Command execution via passthru()", "cwe": "CWE-78"},
        {"regex": r"system\(", "desc": "Command execution via system()", "cwe": "CWE-78"},
        {"regex": r"mysql_query\(", "desc": "Use of deprecated MySQL query (SQLi risk)", "cwe": "CWE-89"},
        {"regex": r"\$_GET\[", "desc": "Direct use of $_GET without sanitization", "cwe": "CWE-20"},
        {"regex": r"\$_POST\[", "desc": "Direct use of $_POST without sanitization", "cwe": "CWE-20"},
        {"regex": r"\$_REQUEST\[", "desc": "Direct use of $_REQUEST without sanitization", "cwe": "CWE-20"},
    ],
    "yaml": [
        {"regex": r"!!python/object", "desc": "YAML unsafe object deserialization", "cwe": "CWE-502"},
        {"regex": r"debug:\s*true", "desc": "Debug mode enabled in YAML config", "cwe": "CWE-693"},
        {"regex": r"password:\s*.+", "desc": "Hardcoded password in YAML", "cwe": "CWE-798"},
        {"regex": r"secret:\s*.+", "desc": "Hardcoded secret in YAML", "cwe": "CWE-798"},
        {"regex": r"api_key:\s*.+", "desc": "Hardcoded API key in YAML", "cwe": "CWE-798"},
    ]
}
